name: Build Desktop Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - run: ant -noinput -buildfile build.xml
      - uses: actions/upload-artifact@v4
        with:
          name: Package
          path: dist
